name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master hw2 ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make main
    - name: Upload artifacts
      uses: actions/upload-artifacts@v3
      with:
        path: a.out
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v3
    - run: make test
